server:
  address: ${SERVER_ADDRESS:0.0.0.0}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/social?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
  data:
    redis:
      host: ${REDIS_HOST:redis}

firefly:
  content:
    base-url: ${CONTENT_BASE_URL:http://content-service:9002}
  user:
    base-url: ${USER_BASE_URL:http://user-service:9001}
